// Eleventy config — production build path.
//   1) passes static assets / robots / sitemap / app-ads through to _site/
//   2) renders index.html and ko|en/*.html as Nunjucks templates with a
//      shared layout (_includes/layouts/base.njk + redirect.njk) and
//      _data/{site,i18n}.js for site-wide variables.
//
// Usage:
//   npm install
//   npm run build           # outputs _site/
//   npm run dev             # local preview at http://localhost:8080

import markdownIt from "markdown-it";
import markdownItAttrs from "markdown-it-attrs";

export default function (eleventyConfig) {
  // Pass-through: copy existing static assets and root-level files.
  // sitemap.xml is now generated by sitemap.njk from _data/pages.js.
  eleventyConfig.addPassthroughCopy("assets");
  eleventyConfig.addPassthroughCopy("robots.txt");
  eleventyConfig.addPassthroughCopy("app-ads.txt");

  // Watch CSS for live-reload during dev.
  eleventyConfig.addWatchTarget("assets/css/");

  // Markdown library with attribute parsing for {.class #id} syntax.
  const md = markdownIt({ html: true, linkify: false, typographer: false });
  md.use(markdownItAttrs);
  eleventyConfig.setLibrary("md", md);

  // Build-time copyright year — replaces the JS fallback in the long run.
  eleventyConfig.addShortcode("year", () => new Date().getFullYear());

  // Format ISO date strings as "YYYY-MM-DD" for sitemap lastmod, etc.
  eleventyConfig.addFilter("isodate", (d) => {
    const date = d instanceof Date ? d : new Date(d);
    return date.toISOString().slice(0, 10);
  });

  return {
    dir: {
      input: ".",
      output: "_site",
      includes: "_includes",
      data: "_data",
    },
    htmlTemplateEngine: "njk",
    markdownTemplateEngine: "njk",
    // html files (index, ko/*, en/*) are now Nunjucks templates with
    // explicit `permalink` in front matter so output paths stay stable.
    templateFormats: ["html", "md", "njk"],
  };
}
